# SimpleWebMedia: Django, MySQL, Nginx, gunicorn, pymysql
# 全てDockerfilerから作成
version: "3.7"
services:
  django:
    container_name: django
    build: ./django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./django/.env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./mysql/
    env_file: ./mysql/.env_db
    volumes:
      - ./mysql_db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    image: simple_webmedia_db
    ports:
      - "3306:3306"

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./django/static:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  mysql_db:
